export default {
  login: "cent-kanayo",
  id: 82293746,
  node_id: "MDQ6VXNlcjgyMjkzNzQ2",
  avatar_url: "https://avatars.githubusercontent.com/u/82293746?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/cent-kanayo",
  html_url: "https://github.com/cent-kanayo",
  followers_url: "https://api.github.com/users/cent-kanayo/followers",
  following_url:
    "https://api.github.com/users/cent-kanayo/following{/other_user}",
  gists_url: "https://api.github.com/users/cent-kanayo/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/cent-kanayo/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/cent-kanayo/subscriptions",
  organizations_url: "https://api.github.com/users/cent-kanayo/orgs",
  repos_url: "https://api.github.com/users/cent-kanayo/repos",
  events_url: "https://api.github.com/users/cent-kanayo/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/cent-kanayo/received_events",
  type: "User",
  site_admin: false,
  name: "Cent Kanayo",
  company: null,
  blog: "",
  location: "Lagos, Nigeria",
  email: null,
  hireable: null,
  bio: "I am an entry-level frontend developer. I love what I do and I am passionate about it. I am open to collaborations",
  twitter_username: "centkanayo10",
  public_repos: 23,
  public_gists: 0,
  followers: 1,
  following: 6,
  created_at: "2021-04-10T23:21:10Z",
  updated_at: "2022-07-15T15:41:17Z",
};
